export * from './About/About';
export * from './InterfaceSlider/InterfaceSlider';
export * from './MyWave/MyWave';
export * from './Pricing/Pricing';
export * from './Showreel/Showreel';
export * from './Watch/Watch';
export * from './YandexMusic/YandexMusic';
export * from './YangoPlans/YangoPlans';
export * from './YangoPlus/YangoPlus';
